project_id = "implgfeegibmaxerblkc"

[functions.upload-dataset]
verify_jwt = true

[functions.process-ml-model]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.analyze-content]
verify_jwt = true